version: '3.7'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=cygxe6-Myhmub-godjub
      - INFLUXDB_URL=http://localhost:8086
    networks:
      - influxnetwork

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

  extract-data:
    build:
      context: ./extract
      dockerfile: Dockerfile
    volumes:
      - ./extract:/app
    networks:
      - influxnetwork
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=cygxe6-Myhmub-godjub
      - INFLUXDB_URL=http://localhost:8086
      - INFLUXDB_TOKEN=C1szqH2SzsFz0gkev0wdU0vBaWCZoYxeA_AWkFPSMRrAoLITtiQOY_Cv95KDcFLwa7Uvv-83DehV2s6TjhRFjQ==
    depends_on:
      - influxdb
      - grafana

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    networks:
      - influxnetwork
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    networks:
      - influxnetwork
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - 'KAFKA_LISTENERS=PLAINTEXT://:9092'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  influxdb-storage:
  grafana-storage:

networks:
  influxnetwork:
