apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: apache/nifi:latest
        ports:
        - containerPort: 8443
        env:
        - name: SINGLE_USER_CREDENTIALS_USERNAME
          value: "admin"
        - name: SINGLE_USER_CREDENTIALS_PASSWORD
          value: "ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB"
        volumeMounts:
        - name: nifi-data
          mountPath: /opt/nifi/nifi-current/data
        - name: nifi-logs
          mountPath: /opt/nifi/logs
      volumes:
      - name: nifi-data
        persistentVolumeClaim:
          claimName: nifi-data-pvc
      - name: nifi-logs
        persistentVolumeClaim:
          claimName: nifi-logs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nifi
spec:
  type: NodePort
  ports:
    - port: 8443
      targetPort: 8443
      nodePort: 30443
  selector:
    app: nifi
