filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

logging.to_files: false
logging.level: info  # Adjust log level as needed

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~