# Use the official Python 3.10 image
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the local test.py file to the container's working directory
COPY test.py .

# Define the command to run when the container starts
CMD ["python", "./test.py"]